const data = [
      "The Shawshank Redemption",
      "The Godfather",
      "The Dark Knight",
      "Pulp Fiction",
      "Forrest Gump",
      "Inception",
      "Fight Club",
      "The Matrix",
      "The Lord of the Rings: The Return of the King",
      "Star Wars: Episode V - The Empire Strikes Back",
      "The Lord of the Rings: The Fellowship of the Ring",
      "Interstellar",
      "The Lord of the Rings: The Two Towers",
      "The Silence of the Lambs",
      "Saving Private Ryan",
      "Schindler's List",
      "The Green Mile",
      "Gladiator",
      "The Prestige",
      "The Departed",
      "The Lion King",
      "Back to the Future",
      "Terminator 2: Judgment Day",
      "The Dark Knight Rises",
      "Django Unchained",
      "The Godfather: Part II",
      "The Avengers",
      "Inglourious Basterds",
      "The Wolf of Wall Street",
      "The Social Network",
      "Se7en",
      "The Usual Suspects",
      "Braveheart",
      "The Truman Show",
      "Jurassic Park",
      "The Sixth Sense",
      "Titanic",
      "Avatar",
      "The Incredibles",
      "Finding Nemo",
      "Toy Story",
      "Toy Story 3",
      "Up",
      "WALL-E",
      "Monsters, Inc.",
      "Ratatouille",
      "Coco",
      "Inside Out",
      "The Lion King (2019)"
    ];
    
export default data;
